help/developer/installation-requirements.md, help/developer/setup-configuration-web.md, help/developer/system-requirements.md
=> Fixing the Web SDK requirement for running from 4.6.1 to 4.6.2+.

azure-pipelines.yml
adding a pipeline file for building the documentation in Azure DevOps for issue #1
=> Azure pipelines setup

help/developer/third-party-software.md
Fix links to licenses requested by Yuu in Third Party Software topic
=> Fix links to licenses in Third Party Software topic.

help/developer/desktop-sdk/api-reference-desktop.md, help/developer/desktop-sdk/using-the-desktop-sdk/configuring-revealview-desktop.md, help/developer/desktop-sdk/using-the-desktop-sdk/creating-visualizations-dashboards-desktop.md, help/developer/desktop-sdk/using-the-desktop-sdk/dashboard-linking-desktop.md, help/developer/desktop-sdk/using-the-desktop-sdk/editing-saving-dashboards-desktop.md, help/developer/desktop-sdk/using-the-desktop-sdk/handling-click-events-desktop.md, help/developer/desktop-sdk/using-the-desktop-sdk/in-memory-data-desktop.md, help/developer/desktop-sdk/using-the-desktop-sdk/loading-dashboards-desktop.md, help/developer/desktop-sdk/using-the-desktop-sdk/maximizing-visualizations-desktop.md, help/developer/desktop-sdk/using-the-desktop-sdk/providing-credentials-datasources-desktop.md, help/developer/desktop-sdk/using-the-desktop-sdk/replacing-data-sources-desktop.md, help/developer/desktop-sdk/using-the-desktop-sdk/setting-dynamic-filters-desktop.md, help/developer/desktop-sdk/using-the-desktop-sdk/setting-initial-filters-desktop.md, help/developer/setup-configuration-web.md, help/developer/web-sdk/using-the-client-sdk/configuring-revealview-client-web.md, help/developer/web-sdk/using-the-client-sdk/creating-visualizations-dashboards-client-web.md, help/developer/web-sdk/using-the-client-sdk/dashboard-linking-client-web.md, help/developer/web-sdk/using-the-client-sdk/editing-saving-dashboards-client-web.md, help/developer/web-sdk/using-the-client-sdk/handling-click-events-client-web.md, help/developer/web-sdk/using-the-client-sdk/maximizing-visualizations-client-web.md, help/developer/web-sdk/using-the-client-sdk/setting-dynamic-filters-client-web.md, help/developer/web-sdk/using-the-client-sdk/setting-initial-filters-client-web.md, help/developer/web-sdk/using-the-client-sdk/setup-configuration-client-web.md, help/developer/web-sdk/using-the-server-sdk/Providing-Credentials-Datasources-server-web.md, help/developer/web-sdk/using-the-server-sdk/in-memory-data-server-web.md, help/developer/web-sdk/using-the-server-sdk/loading-dashboards-server-web.md, help/developer/web-sdk/using-the-server-sdk/replacing-data-sources-server-web.md
I basically changed:
[**class/method**](url)
to:
__class/method__
=> Removing all API links from topics.

templates/reveal/styles/main.css
I believe this is the file I need to update.
I'm not sure  because in the past when I changed the file locally, it was overwritten by the server every time I launched a build.
Also, this changes cannot be final until we actually see them reflected in staging and we are all happy with the outcome.
=> First attempt to update the CSS

help/developer/release-information/release-notes.md
Edit: *Release version still unknown.
=> Add release notes for end of March release (version still known).

en/dashboard-tutorials/finance-dashboard/adding-other-visualizations.md, en/dashboard-tutorials/finance-dashboard/getting-started.md, en/dashboard-tutorials/manufacturing-dashboard/adding-other-visualizations.md, en/dashboard-tutorials/manufacturing-dashboard/getting-started.md, en/dashboard-tutorials/sales-dashboard/adding-other-visualizations.md, en/dashboard-tutorials/sales-dashboard/getting-started.md, en/dashboard-tutorials/social-dashboard/adding-other-visualizations.md, en/dashboard-tutorials/social-dashboard/getting-started.md, en/data-visualizations/overview.md, en/datasources/supported-data-sources/web-resource.md, en/visualization-tutorials/candlestick-chart.md, en/visualization-tutorials/gauge-charts.md, en/visualization-tutorials/image-chart.md, en/visualization-tutorials/kpi-gauge.md, en/visualization-tutorials/ohlc-chart.md, en/visualization-tutorials/overview.md, en/visualization-tutorials/simple-charts.md, en/visualization-tutorials/sparkline-charts.md, en/visualization-tutorials/stacked-charts.md, en/visualization-tutorials/text-view.md
As we discussed - I made the changes in a separate branch and I am creating a pull request now.
=> A link to file is changed to use https

en/developer/desktop-sdk/using-the-desktop-sdk/loading-dashboards.md
I have added an explanation and code snippet for loading dashboard from a json file scenario.
Please, feel free to add comments and suggest improvements.
=> Changes in LoadingDashboards(DesktopSDK)

docfx.json, index.html
Updates include:
- Modified docfx.json to add globalmeta variable for use within templates
- Added GTM snippets to index.html (in root and in language directory)
=> Added globalmeta var and added gtm to template

en/web/loading-dashboards.md
The loadDashboardAsync method is the one returning a promise. we might want to mention it somewhere here. Not sure what would be the best place though.
=> Fixing the loading topic that was incorrectly stating the $.ig.RVDashboard.loadDashboard returns a promise

en/dashboards/managing-dashboards.md
=> vsy-(managing dashboards)

en/datasources/supported-data-sources/microsoft-analysis-services.md
Made some changes when it comes to width and bullet points
=> vsy-updated the article

en/datasources/supported-data-sources/microsoft-analysis-services.md, en/datasources/supported-data-sources/postgresql.md, en/datasources/supported-data-sources/salesforce.md, en/datasources/supported-data-sources/sybase.md, en/datasources/supported-data-sources/web-resource.md
If the Reveal local and the Slingshot staging are the same, it should be ready for production.
=> vsy-last changes

en/web/overview.md, en/web/toc.yml
Moved the Getting started topic up on level.
=> reordered ToC for web

i18n/ja/code.json
=> Translated to JP in code.json

i18n/ja/docusaurus-plugin-content-docs/current/web/_configuring-server-java-export.md, i18n/ja/docusaurus-plugin-content-docs/current/web/configuring-server-tomcat.md, i18n/ja/docusaurus-plugin-content-docs/current/web/loading-dashboards.md
Translated to JP in _configuring-server-java-export.md
=> Translated to JP in _configuring-server-java-export.md

docs/web/adding-data-sources/excel-file.md, docs/web/adding-license-key.md, docs/web/authentication.md, docs/web/loading-dashboards.md, docs/web/release-notes.md, docs/web/replacing-data-sources/excel-file.md, docs/web/replacing-data-sources/ms-sql-server.md, docs/web/replacing-datasources.md, docs/web/server-export.md, docs/web/user-context.md, i18n/ja/docusaurus-plugin-content-docs/current/web/adding-data-sources/excel-file.md, i18n/ja/docusaurus-plugin-content-docs/current/web/adding-license-key.md, i18n/ja/docusaurus-plugin-content-docs/current/web/authentication.md, i18n/ja/docusaurus-plugin-content-docs/current/web/loading-dashboards.md, i18n/ja/docusaurus-plugin-content-docs/current/web/release-notes.md, i18n/ja/docusaurus-plugin-content-docs/current/web/replacing-data-sources/excel-file.md, i18n/ja/docusaurus-plugin-content-docs/current/web/replacing-data-sources/ms-sql-server.md, i18n/ja/docusaurus-plugin-content-docs/current/web/replacing-datasources.md, i18n/ja/docusaurus-plugin-content-docs/current/web/server-export.md, i18n/ja/docusaurus-plugin-content-docs/current/web/user-context.md, package-lock.json, package.json
- Upgraded the Docusaurus dependency.
- Implemented new query string feature for code tabs (you can now deep link to a topic and specific code tab)
=> Upgrade Docusaurus 2.3.0

docs/web/system-requirements.md, i18n/ja/docusaurus-plugin-content-docs/current/web/system-requirements.md, package-lock.json, package.json
updated the system requirements for the node 0.7.3 release
=> Updated system requirements

docs/web/adding-data-sources/ms-sql-server.md, docs/web/datasources.md, docs/web/server-export.md, i18n/ja/docusaurus-plugin-content-docs/current/web/adding-data-sources/ms-sql-server.md, i18n/ja/docusaurus-plugin-content-docs/current/web/datasources.md, i18n/ja/docusaurus-plugin-content-docs/current/web/server-export.md, sidebars.js
I am experimenting with a new structure for data source topics. Want to get them in staging for review before creating new data source topics
=> Data sources topic restructure

docs/web/loading-dashboards.md, i18n/ja/docusaurus-plugin-content-docs/current/web/loading-dashboards.md
Minor fix for the sample code on setBaseUrl port number (both EN and JA)
=> Minor fix for the sample code on setBaseUrl port number

i18n/ja/docusaurus-plugin-content-docs/current/web/release-notes.md, i18n/ja/docusaurus-plugin-content-docs/current/wpf/release-notes.md, sidebars.js
=> Updated Japanese release notes

docs/web/adding-license-key.md, docs/web/getting-started-angular.md, docs/web/getting-started-aspnet.md, docs/web/getting-started-javascript.md, docs/web/getting-started-react.md, docs/web/getting-started-spring-boot-jersey.md, docs/web/install-client-sdk.md, docs/web/install-server-sdk.md, docs/web/system-requirements.md, docs/wpf/adding-license-key.md, docusaurus.config.js, i18n/ja/docusaurus-plugin-content-docs/current/web/adding-license-key.md, i18n/ja/docusaurus-plugin-content-docs/current/web/getting-started-angular.md, i18n/ja/docusaurus-plugin-content-docs/current/web/getting-started-aspnet.md, i18n/ja/docusaurus-plugin-content-docs/current/web/getting-started-javascript.md, i18n/ja/docusaurus-plugin-content-docs/current/web/getting-started-react.md, i18n/ja/docusaurus-plugin-content-docs/current/web/getting-started-spring-boot-jersey.md, i18n/ja/docusaurus-plugin-content-docs/current/web/install-client-sdk.md, i18n/ja/docusaurus-plugin-content-docs/current/web/install-server-sdk.md, i18n/ja/docusaurus-plugin-content-docs/current/web/system-requirements.md, i18n/ja/docusaurus-plugin-content-docs/current/wpf/adding-license-key.md, plugins/remark/replace-variables.js, sidebars.js
- Updating topics for v1.6.0
- added dynamic sdk versioning for code snippets and links
=> Updating topics for v1.6.0

src/components/DataSourcesTable/index.tsx
Commented out data sources that we don't want to advertise due to known issues
=> updated data source list

docs/web/release-notes.md, i18n/ja/docusaurus-plugin-content-docs/current/web/release-notes.md
This is a small patch release to fix a dependency
=> added release notes for 1.6.3

docs/web/getting-started-spring-boot-jersey.md
Updated the Spring Boot documentation to reflect the changes needed for Spring Boot 3.x
=> Updated required versions, changed javax references to jakarta ones.

docs/user/fields/calculated/math.md, docs/user/filters-dashboard-properties.md, docs/user/tutorials-candlestick.md, docs/user/tutorials-kpi-gauge.md, docs/user/tutorials-overview.md, docs/user/tutorials-simple-charts.md, docs/user/visualization-types/diy-visualization-step-by-step.md, docs/user/visualization-types/diy-visualizations.md, docs/user/visualization-types/financial-charts.md, docs/user/visualization-types/map-image-tiles.md
…ties format; update Math fields format
=> Update remaining wrong words and format
